Config = {}
Config.UseTarget = GetConvar('UseTarget', 'true') == 'true'

-- Deliveries
Config.ShopsInvJsonFile = './json/shops-inventory.json'
Config.TruckDeposit = 125
Config.MaxDeliveries = 20
Config.DeliveryPrice = 500
Config.RewardItem = 'cryptostick'
Config.Fuel = 'LegacyFuel'

Config.DeliveryLocations = {
    ['main'] = { label = 'GO Postal', coords = vector4(69.0862, 127.6753, 79.2123, 156.7736) },
    ['vehicleWithdraw'] = vector4(71.9318, 120.8389, 79.0823, 160.5110),
    ['vehicleDeposit'] = vector3(62.7282, 124.9846, 79.0926),
    ['stores'] = {} -- auto generated
}

Config.Vehicles = {
    ['boxville2'] = { ['label'] = 'Boxville StepVan', ['cargodoors'] = { [0] = 2, [1] = 3 }, ['trunkpos'] = 1.5 },
}

Config.Products = {
	['fishshop'] = {
        { name = 'fishingrod',         price = 50,   amount = 10 },
		{ name = 'fishingbait',         price = 2,   amount = 500 },
	},
	['pokemonshop'] = {
        { name = 'boosterpack',         price = 40,   amount = 100 },
	},
	['mineshop'] = {
        { name = 'phone',         price = 1500,   amount = 10 },
        { name = 'water_bottle',  price = 500,   amount = 10 },
		{ name = 'sandwich',  price = 5,   amount = 10 },
		{ name = 'weapon_flashlight',  price = 15,   amount = 10 },
		{ name = 'bandage',  price = 5,   amount = 10 },
		{ name = 'goldpan',  price = 20,   amount = 10 },
		{ name = 'pickaxe',  price = 50,   amount = 10 },
		{ name = 'miningdrill',  price = 200,   amount = 10 },
		{ name = 'mininglaser',  price = 5000,   amount = 10 },
		{ name = 'drillbit',  price = 5,   amount = 10 },
	},
	['phoneshop'] = {
        { name = 'phone',         price = 1500,   amount = 10 },
        { name = 'camera',  price = 500,   amount = 10 },
    },
    ['normal'] = {
        { name = 'tosti',         price = 2,   amount = 50 },
        { name = 'water_bottle',  price = 2,   amount = 50 },
        { name = 'kurkakola',     price = 2,   amount = 50 },
        { name = 'twerks_candy',  price = 2,   amount = 50 },
        { name = 'snikkel_candy', price = 2,   amount = 50 },
        { name = 'sandwich',      price = 2,   amount = 50 },
        { name = 'beer',          price = 7,   amount = 50 },
        { name = 'whiskey',       price = 10,  amount = 50 },
        { name = 'vodka',         price = 12,  amount = 50 },
        { name = 'bandage',       price = 100, amount = 50 },
        { name = 'lighter',       price = 2,   amount = 50 },
        { name = 'rolling_paper', price = 2,   amount = 5000 },
    },
    ['liquor'] = {
        { name = 'beer',    price = 7,  amount = 50 },
        { name = 'whiskey', price = 10, amount = 50 },
        { name = 'vodka',   price = 12, amount = 50 },
    },
    ['hardware'] = {
        { name = 'lockpick',          price = 200, amount = 50 },
        { name = 'weapon_wrench',     price = 250, amount = 250 },
        { name = 'weapon_hammer',     price = 250, amount = 250 },
        { name = 'repairkit',         price = 250, amount = 50, requiredJob = { 'mechanic', 'police' } },
        { name = 'screwdriverset',    price = 350, amount = 50 },
        { name = 'phone',             price = 850, amount = 50 },
        { name = 'radio',             price = 250, amount = 50 },
        { name = 'binoculars',        price = 50,  amount = 50 },
        { name = 'firework1',         price = 50,  amount = 50 },
        { name = 'firework2',         price = 50,  amount = 50 },
        { name = 'firework3',         price = 50,  amount = 50 },
        { name = 'firework4',         price = 50,  amount = 50 },
        { name = 'fitbit',            price = 400, amount = 150 },
        { name = 'cleaningkit',       price = 150, amount = 150 },
        { name = 'advancedrepairkit', price = 500, amount = 50, requiredJob = 'mechanic' },
    },
    ['shishabar'] = {
        { name = 'bong',          price = 100,  amount = 5 },
        { name = 'lighter',		 price = 2, amount = 50 },
        { name = 'banana_kush_weed', price = 50,  amount = 10 },
        { name = 'purple_haze_weed', price = 50,   amount = 10 },
        { name = 'og_kush_weed',  price = 50,   amount = 10 },
		{ name = 'blue_dream_weed',  price = 50,   amount = 10 },
    },
    ['ciggs'] = {
        { name = 'lighter', price = 5, amount = 50 },
        { name = 'redw',   price = 20,  amount = 50 },
		{ name = 'marlboro',   price = 20,  amount = 50 },
		{ name = 'cubancigar',   price = 500,  amount = 50 },
		{ name = 'davidoffcigar',   price = 250,  amount = 50 },
    },
    ['seaword'] = {
        { name = 'parachute',   price = 200, amount = 10 },
        { name = 'binoculars',  price = 10,   amount = 50 },
        { name = 'diving_gear', price = 500, amount = 10 },
        { name = 'diving_fill', price = 10,  amount = 10 },
    },
    ['weapons'] = {
        { name = 'weapon_knife',         price = 250,  amount = 250 },
        { name = 'weapon_bat',           price = 250,  amount = 250 },
        { name = 'weapon_hatchet',       price = 250,  amount = 250 },
        { name = 'pistol_ammo',          price = 250,  amount = 250, requiredLicense = 'weapon' },
        { name = 'weapon_pistol',        price = 2500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_snspistol',     price = 1500, amount = 5,   requiredLicense = 'weapon' },
        { name = 'weapon_vintagepistol', price = 4000, amount = 5,   requiredLicense = 'weapon' },
    },
    ['blackmarket'] = {
        { name = 'security_card_01',  price = 5000, amount = 50 },
        { name = 'security_card_02',  price = 5000, amount = 50 },
        { name = 'advanced_lockpick', price = 5000, amount = 50 },
        { name = 'electronickit',     price = 5000, amount = 50 },
        { name = 'gatecrack',         price = 5000, amount = 50 },
        { name = 'thermite',          price = 5000, amount = 50 },
        { name = 'trojan_usb',        price = 5000, amount = 50 },
        { name = 'drill',             price = 5000, amount = 50 },
        { name = 'radioscanner',      price = 5000, amount = 50 },
        { name = 'cryptostick',       price = 5000, amount = 50 },
        { name = 'joint',             price = 5000, amount = 50 },
        { name = 'cokebaggy',         price = 5000, amount = 50 },
        { name = 'crack_baggy',       price = 5000, amount = 50 },
        { name = 'xtcbaggy',          price = 5000, amount = 50 },
        { name = 'coke_brick',        price = 5000, amount = 50 },
        { name = 'weed_brick',        price = 5000, amount = 50 },
        { name = 'coke_small_brick',  price = 5000, amount = 50 },
        { name = 'oxy',               price = 5000, amount = 50 },
        { name = 'meth',              price = 5000, amount = 50 },
        { name = 'weed_whitewidow',   price = 5000, amount = 50 },
        { name = 'weed_skunk',        price = 5000, amount = 50 },
        { name = 'weed_purplehaze',   price = 5000, amount = 50 },
        { name = 'weed_ogkush',       price = 5000, amount = 50 },
        { name = 'weed_amnesia',      price = 5000, amount = 50 },
        { name = 'weed_ak47',         price = 5000, amount = 50 },
        { name = 'markedbills',       price = 5000, amount = 50, info = { worth = 5000 } },
    },
    ['prison'] = {
        { name = 'sandwich',     price = 4, amount = 50 },
        { name = 'water_bottle', price = 4, amount = 50 },
    },
    ['police'] = {
        { name = 'weapon_pistol',       price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_PI_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_stungun',      price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_pumpshotgun',  price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_smg',          price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_SCOPE_MACRO_02', label = '1x Scope' }, { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' } } } },
        { name = 'weapon_carbinerifle', price = 0, amount = 50, info = { attachments = { { component = 'COMPONENT_AT_AR_FLSH', label = 'Flashlight' }, { component = 'COMPONENT_AT_SCOPE_MEDIUM', label = '3x Scope' } } } },
        { name = 'weapon_nightstick',   price = 0, amount = 50 },
        { name = 'weapon_flashlight',   price = 0, amount = 50 },
        { name = 'pistol_ammo',         price = 0, amount = 50 },
        { name = 'smg_ammo',            price = 0, amount = 50 },
        { name = 'shotgun_ammo',        price = 0, amount = 50 },
        { name = 'rifle_ammo',          price = 0, amount = 50 },
        { name = 'handcuffs',           price = 0, amount = 50 },
        { name = 'empty_evidence_bag',  price = 0, amount = 50 },
        { name = 'police_stormram',     price = 0, amount = 50 },
        { name = 'armor',               price = 0, amount = 50 },
        { name = 'radio',               price = 0, amount = 50 },
        { name = 'heavyarmor',          price = 0, amount = 50 },
    },
    ['ambulance'] = {
        { name = 'radio',                   price = 0, amount = 50 },
        { name = 'bandage',                 price = 0, amount = 50 },
        { name = 'painkillers',             price = 0, amount = 50 },
        { name = 'firstaid',                price = 0, amount = 50 },
        { name = 'weapon_flashlight',       price = 0, amount = 50 },
        { name = 'weapon_fireextinguisher', price = 0, amount = 50 },
    },
    ['levelshop'] = {
        { name = 'level1',                  price = 1000, amount = 1},
        { name = 'level2',                  price = 1000, amount = 1, requiredLevel = 1  },
        { name = 'level3',                  price = 1000, amount = 1, requiredLevel = 2  },
        { name = 'level4',                  price = 1000, amount = 1, requiredLevel = 3  },
        { name = 'level5',                  price = 1000, amount = 1, requiredLevel = 4  },
        { name = 'level6',                  price = 1000, amount = 1, requiredLevel = 5  },
        { name = 'level7',                  price = 1000, amount = 1, requiredLevel = 6  },
        { name = 'level8',                  price = 1000, amount = 1, requiredLevel = 7  },
        { name = 'level9',                  price = 1000, amount = 1, requiredLevel = 8  },
        { name = 'level10',                 price = 1000, amount = 1, requiredLevel = 9  },
        { name = 'level11',                 price = 1000, amount = 1, requiredLevel = 10 },
        { name = 'level12',                 price = 1000, amount = 1, requiredLevel = 11 },
        { name = 'level13',                 price = 1000, amount = 1, requiredLevel = 12 },
        { name = 'level14',                 price = 1000, amount = 1, requiredLevel = 13 },
        { name = 'level15',                 price = 1000, amount = 1, requiredLevel = 14 },
        { name = 'level16',                 price = 1000, amount = 1, requiredLevel = 15 },
        { name = 'level17',                 price = 1000, amount = 1, requiredLevel = 16 },
        { name = 'level18',                 price = 1000, amount = 1, requiredLevel = 17 },
        { name = 'level19',                 price = 1000, amount = 1, requiredLevel = 18 },
        { name = 'level20',                 price = 1000, amount = 1, requiredLevel = 19 },
        { name = 'level21',                 price = 1000, amount = 1, requiredLevel = 20 },
        { name = 'level22',                 price = 1000, amount = 1, requiredLevel = 21 },
        { name = 'level23',                 price = 1000, amount = 1, requiredLevel = 22 },
        { name = 'level24',                 price = 1000, amount = 1, requiredLevel = 23 },
        { name = 'level25',                 price = 1000, amount = 1, requiredLevel = 24 },
        { name = 'level26',                 price = 1000, amount = 1, requiredLevel = 25 },
        { name = 'level27',                 price = 1000, amount = 1, requiredLevel = 26 },
        { name = 'level28',                 price = 1000, amount = 1, requiredLevel = 27 },
        { name = 'level29',                 price = 1000, amount = 1, requiredLevel = 28 },
        { name = 'level30',                 price = 1000, amount = 1, requiredLevel = 29 },
        { name = 'level31',                 price = 1000, amount = 1, requiredLevel = 30 },
        { name = 'level32',                 price = 1000, amount = 1, requiredLevel = 31 },
        { name = 'level33',                 price = 1000, amount = 1, requiredLevel = 32 },
        { name = 'level34',                 price = 1000, amount = 1, requiredLevel = 33 },
        { name = 'level35',                 price = 1000, amount = 1, requiredLevel = 34 },
        { name = 'level36',                 price = 1000, amount = 1, requiredLevel = 35 },
        { name = 'level37',                 price = 1000, amount = 1, requiredLevel = 36 },
        { name = 'level38',                 price = 1000, amount = 1, requiredLevel = 37 },
        { name = 'level39',                 price = 1000, amount = 1, requiredLevel = 38 },
        { name = 'level40',                 price = 1000, amount = 1, requiredLevel = 39 },
        { name = 'level41',                 price = 1000, amount = 1, requiredLevel = 40 },
        { name = 'level42',                 price = 1000, amount = 1, requiredLevel = 41 },
        { name = 'level43',                 price = 1000, amount = 1, requiredLevel = 42 },
        { name = 'level44',                 price = 1000, amount = 1, requiredLevel = 43 },
        { name = 'level45',                 price = 1000, amount = 1, requiredLevel = 44 },
        { name = 'level46',                 price = 1000, amount = 1, requiredLevel = 45 },
        { name = 'level47',                 price = 1000, amount = 1, requiredLevel = 46 },
        { name = 'level48',                 price = 1000, amount = 1, requiredLevel = 47 },
        { name = 'level49',                 price = 1000, amount = 1, requiredLevel = 48 },
        { name = 'level50',                 price = 1000, amount = 1, requiredLevel = 49 }
    },


    ['performance'] = {
        { name = 'mechanic_tools',          price = 100, amount = 50, requiredLevel = 0  },
        { name = 'toolbox',                 price = 100, amount = 50, requiredLevel = 0  },
        { name = 'ducttape',                price = 100, amount = 50, requiredLevel = 0  },
        { name = 'sparkplugs',              price = 100, amount = 50, requiredLevel = 0  },
        { name = 'carbattery',              price = 100, amount = 50, requiredLevel = 0  },
        { name = 'axleparts',               price = 100, amount = 50, requiredLevel = 0  },
        { name = 'sparetire',               price = 100, amount = 50, requiredLevel = 0  },
        { name = 'engine1',                 price = 5000, amount = 50, requiredLevel = 1  },
        { name = 'engine2',                 price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'engine3',                 price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'engine4',                 price = 5000, amount = 50, requiredLevel = 7  },
        { name = 'transmission1',           price = 5000, amount = 50, requiredLevel = 1  },
        { name = 'transmission2',           price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'transmission3',           price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'brakes1',                 price = 5000, amount = 50, requiredLevel = 1  },
        { name = 'brakes2',                 price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'brakes3',                 price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'suspension1',             price = 5000, amount = 50, requiredLevel = 1  },
        { name = 'suspension2',             price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'suspension3',             price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'suspension4',             price = 5000, amount = 50, requiredLevel = 7  },
        { name = 'suspension5',             price = 5000, amount = 50, requiredLevel = 8  },
        { name = 'oilp1',                   price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'oilp2',                   price = 5000, amount = 50, requiredLevel = 7  },
        { name = 'oilp3',                   price = 5000, amount = 50, requiredLevel = 9  },
        { name = 'drives1',                 price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'drives2',                 price = 5000, amount = 50, requiredLevel = 7  },
        { name = 'drives3',                 price = 5000, amount = 50, requiredLevel = 9  },
        { name = 'cylind1',                 price = 5000, amount = 50, requiredLevel = 6  },
        { name = 'cylind2',                 price = 5000, amount = 50, requiredLevel = 8  },
        { name = 'cylind3',                 price = 5000, amount = 50, requiredLevel = 10  },
        { name = 'cables1',                 price = 5000, amount = 50, requiredLevel = 5  },
        { name = 'cables2',                 price = 5000, amount = 50, requiredLevel = 7  },
        { name = 'cables3',                 price = 5000, amount = 50, requiredLevel = 9  },
        { name = 'fueltank1',               price = 5000, amount = 50, requiredLevel = 6  },
        { name = 'fueltank2',               price = 5000, amount = 50, requiredLevel = 8  },
        { name = 'fueltank3',               price = 5000, amount = 50, requiredLevel = 10  },
        { name = 'antilag',                 price = 5000, amount = 50, requiredLevel = 10  },
    },
    ['cosmetic'] = {
        { name = 'underglow_controller',    price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'underglow',               price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'headlights',              price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'tint_supplies',           price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'customplate',             price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'hood',                    price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'roof',                    price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'spoiler',                 price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'bumper',                  price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'skirts',                  price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'exhaust',                 price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'seat',                    price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'rollcage',                price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'rims',                    price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'livery',                  price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'paintcan',                price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'tires',                   price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'horn',                    price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'internals',               price = 5000, amount = 50, requiredLevel = 3  },
        { name = 'externals',               price = 5000, amount = 50, requiredLevel = 3  },
    }
}

Config.Locations = {
    ['levelshop'] = {
        ['label'] = 'Level Up Shop',
        ['coords'] = vector4(-542.73, -208.04, 37.65, 210.11),
        ['ped'] = 's_m_y_casino_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['levelshop'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-542.99, -207.5, 37.65, 210.72),
        ['useStock'] = false
    },
    -- MECHANICS ITEMS
    ['performance'] = {
        ['label'] = 'Performance Items',
        ['coords'] = vector4(131.06, -3008.15, 7.04, 214.68),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['performance'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = false
    },
    ['cosmetic'] = {
        ['label'] = 'Cosmetic Items',
        ['coords'] = vector4(127.93, -3009.78, 7.04, 226.95),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['cosmetic'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = false
    },
    -- 24/7 Locations
    ['247supermarket'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(24.47, -1346.62, 29.5, 271.66),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(26.45, -1315.51, 29.62, 0.07),
        ['useStock'] = true
    },

    ['247supermarket2'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3039.54, 584.38, 7.91, 17.27),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3047.95, 590.71, 7.62, 19.53)
    },

    ['247supermarket3'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(-3242.97, 1000.01, 12.83, 357.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3245.76, 1005.25, 12.83, 269.45)
    },

    ['247supermarket4'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1728.07, 6415.63, 35.04, 242.95),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1741.76, 6419.61, 35.04, 6.83)
    },

    ['247supermarket5'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(1959.82, 3740.48, 32.34, 301.57),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1963.81, 3750.09, 32.26, 302.46)
    },

    ['247supermarket6'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(549.13, 2670.85, 42.16, 99.39),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(541.54, 2663.53, 42.17, 120.51)
    },

    ['247supermarket7'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2677.47, 3279.76, 55.24, 335.08),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2662.19, 3264.95, 55.24, 168.55)
    },

    ['247supermarket8'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(2556.66, 380.84, 108.62, 356.67),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2553.24, 399.73, 108.56, 344.86)
    },

    ['247supermarket9'] = {
        ['label'] = '24/7 Supermarket',
        ['coords'] = vector4(372.66, 326.98, 103.57, 253.73),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(379.97, 357.3, 102.56, 26.42)
    },

    -- LTD Gasoline Locations
    ['ltdgasoline'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-47.02, -1758.23, 29.42, 45.05),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-40.51, -1747.45, 29.29, 326.39)
    },

    ['ltdgasoline2'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-706.06, -913.97, 19.22, 88.04),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-702.89, -917.44, 19.21, 181.96)
    },

    ['ltdgasoline3'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(-1820.02, 794.03, 138.09, 135.45),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1829.29, 801.49, 138.41, 41.39)
    },

    ['ltdgasoline4'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1164.71, -322.94, 69.21, 101.72),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1160.62, -312.06, 69.28, 3.77)
    },

    ['ltdgasoline5'] = {
        ['label'] = 'LTD Gasoline',
        ['coords'] = vector4(1697.87, 4922.96, 42.06, 324.71),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['normal'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1702.68, 4917.28, 42.22, 139.27)
    },

    -- Rob's Liquor Locations
    ['robsliquor'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1221.58, -908.15, 12.33, 35.49),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1226.92, -901.82, 12.28, 213.26)
    },

    ['robsliquor2'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-1486.59, -377.68, 40.16, 139.51),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1468.29, -387.61, 38.79, 220.13)
    },

    ['robsliquor3'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(-2966.39, 391.42, 15.04, 87.48),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-2961.49, 376.25, 15.02, 111.41)
    },

    ['robsliquor4'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1165.17, 2710.88, 38.16, 179.43),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1194.52, 2722.21, 38.62, 9.37)
    },

    ['robsliquor5'] = {
        ['label'] = 'Rob\'s Liqour',
        ['coords'] = vector4(1134.2, -982.91, 46.42, 277.24),
        ['ped'] = 'mp_m_shopkeep_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-shopping-basket',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['liquor'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1129.73, -989.27, 45.97, 280.98)
    },

    -- Hardware Store Locations
    ['hardware'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(45.68, -1749.04, 29.61, 53.13),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(89.15, -1745.29, 30.09, 315.25)
    },

    ['hardware2'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(2747.71, 3472.85, 55.67, 255.08),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Open Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2704.68, 3457.21, 55.54, 176.28)
    },

    ['hardware3'] = {
        ['label'] = 'Hardware Store',
        ['coords'] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ['ped'] = 'mp_m_waremech_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-wrench',
        ['targetLabel'] = 'Hardware Store',
        ['products'] = Config.Products['hardware'],
        ['showblip'] = true,
        ['blipsprite'] = 402,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-438.25, 6146.9, 31.48, 136.99)
    },

    -- Ammunation Locations
    ['ammunation'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-661.96, -933.53, 21.83, 177.05),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-660.61, -938.14, 21.83, 167.22)
    },
    ['ammunation2'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(809.68, -2159.13, 29.62, 1.43),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(820.97, -2146.7, 28.71, 359.98)
    },
    ['ammunation3'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(1692.67, 3761.38, 34.71, 227.65),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1687.17, 3755.47, 34.34, 163.69)
    },
    ['ammunation4'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-331.23, 6085.37, 31.45, 228.02),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-341.72, 6098.49, 31.32, 11.05)
    },
    ['ammunation5'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(253.63, -51.02, 69.94, 72.91),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(249.0, -50.64, 69.94, 60.71)
    },
    ['ammunation6'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(23.0, -1105.67, 29.8, 162.91),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-5.82, -1107.48, 29.0, 164.32)
    },
    ['ammunation7'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(2567.48, 292.59, 108.73, 349.68),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2578.77, 285.53, 108.61, 277.2)
    },
    ['ammunation8'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1118.59, 2700.05, 18.55, 221.89),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1127.67, 2708.18, 18.8, 41.76)
    },
    ['ammunation9'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(841.92, -1035.32, 28.19, 1.56),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(847.83, -1020.36, 27.88, 88.29)
    },
    ['ammunation10'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-1304.19, -395.12, 36.7, 75.03),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1302.44, -385.23, 36.62, 303.79)
    },
    ['ammunation11'] = {
        ['label'] = 'Ammunation',
        ['type'] = 'weapon',
        ['coords'] = vector4(-3173.31, 1088.85, 20.84, 244.18),
        ['ped'] = 's_m_y_ammucity_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Ammunation',
        ['products'] = Config.Products['weapons'],
        ['showblip'] = true,
        ['blipsprite'] = 110,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-3183.6, 1084.35, 20.84, 68.13)
    },

    -- Weedshop Locations
    ['shishabar'] = {
        ['label'] = 'Shisha Bar',
        ['coords'] = vector4(97.21, 200.53, 108.37, 157.14),
        ['ped'] = 'a_m_y_hippy_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-cannabis',
        ['targetLabel'] = 'Open Shisha Menu',
        ['products'] = Config.Products['shishabar'],
        ['showblip'] = true,
        ['blipsprite'] = 140,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1162.13, -1568.57, 4.39, 328.52)
    },

    -- Sea Word Locations
    ['seaword'] = {
        ['label'] = 'Diving Gear',
        ['coords'] = vector4(-772.48, -1432.74, 1.6, 115.65),
        ['ped'] = 'a_m_y_beach_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_IMPATIENT',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-fish',
        ['targetLabel'] = 'Sea Word',
        ['products'] = Config.Products['seaword'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-772.48, -1432.74, 1.6, 115.65)
    },

    -- Leisure Shop Locations
    ['ciggs'] = {
        ['label'] = 'Ciggs and Cigars',
        ['coords'] = vector4(277.13, -1022.91, 29.21, 230.45),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['ciggs'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(277.13, -1022.91, 29.21, 230.45)
    },

    ['police'] = {
        ['label'] = 'Police Shop',
        ['coords'] = vector4(461.8498, -981.0677, 30.6896, 91.5892),
        ['ped'] = 'mp_m_securoguard_01',
        ['scenario'] = 'WORLD_HUMAN_COP_IDLES',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-gun',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['police'],
        ['delivery'] = vector4(459.0441, -1008.0366, 28.2627, 271.4695),
        ['requiredJob'] = 'police',
    },

    ['ambulance'] = {
        ['label'] = 'Ambulance Shop',
        ['coords'] = vector4(309.93, -602.94, 43.29, 71.0820),
        ['ped'] = 's_m_m_doctor_01',
        ['scenario'] = 'WORLD_HUMAN_STAND_MOBILE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-hand',
        ['targetLabel'] = 'Open Armory',
        ['products'] = Config.Products['ambulance'],
        ['delivery'] = vector4(283.5821, -614.8570, 43.3792, 159.2903),
        ['requiredJob'] = 'ambulance'
    },

    ['mechanic'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-343.66, -140.78, 39.02, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-354.3936, -128.2882, 39.4307, 251.4931),
        ['requiredJob'] = 'mechanic',
    },

    ['mechanic2'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(1189.36, 2641.00, 38.44, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(1189.9852, 2651.1873, 37.8351, 317.7137),
        ['requiredJob'] = 'mechanic2'
    },

    ['mechanic3'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-1156.56, -1999.85, 13.19, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-1131.9661, -1972.0144, 13.1603, 358.8637),
        ['requiredJob'] = 'mechanic3'
    },

    ['bennys'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(-195.80, -1318.24, 31.08, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(-232.5028, -1311.7202, 31.2960, 180.3716),
        ['requiredJob'] = 'bennys'
    },

    ['beeker'] = {
        ['label'] = 'Mechanic Shop',
        ['coords'] = vector4(100.92, 6616.00, 32.47, 0),
        ['products'] = Config.Products['mechanic'],
        ['delivery'] = vector4(119.3033, 6626.7358, 31.9558, 46.1566),
        ['requiredJob'] = 'beeker'
    },

    ['prison'] = {
        ['label'] = 'Canteen Shop',
        ['coords'] = vector4(1777.59, 2560.52, 44.62, 187.83),
        ['ped'] = false,
        ['products'] = Config.Products['prison'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(1845.8175, 2585.9312, 45.6721, 96.7577)
    },

    ['blackmarket'] = {
        ['label'] = 'Black Market',
        ['coords'] = vector4(-594.7032, -1616.3647, 33.0105, 170.6846),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 1.5,
        ['targetIcon'] = 'fas fa-clipboard',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['blackmarket'],
        ['delivery'] = vector4(-428.6385, -1728.1962, 19.7838, 75.6646)
    },
	
	['phoneshop'] = {
        ['label'] = 'Phone Shop',
        ['coords'] = vector4(-1530.16, -402.04, 35.64, 227.99),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 2.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['phoneshop'],
        ['showblip'] = true,
        ['blipsprite'] = 52,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-1530.16, -402.04, 35.64, 227.99)
	},
	
	['mineshop'] = {
        ['label'] = 'Mine Shop',
        ['coords'] = vector4(2960.06, 2753.8, 43.71, 198.95),
        ['ped'] = 'a_m_y_smartcaspat_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 2.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['mineshop'],
        ['showblip'] = true,
        ['blipsprite'] = 527,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(2960.06, 2753.8, 43.71, 198.95)
	},
	
	['pokemonshop'] = {
        ['label'] = 'Buy Pokemon Cards',
        ['coords'] = vector4(-143.64, 229.9, 94.94, 0.94),
        ['ped'] = 'u_m_m_streetart_01',
        ['scenario'] = 'WORLD_HUMAN_CLIPBOARD',
        ['radius'] = 2.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['pokemonshop'],
        ['showblip'] = true,
        ['blipsprite'] = 671,
        ['blipscale'] = 0.8,
        ['blipcolor'] = 0,
        ['delivery'] = vector4(-143.64, 229.9, 94.94, 0.94)
	},
	
	['fishshop'] = {
        ['label'] = 'Fishing Rod Shop',
        ['coords'] = vector4(-1593.88, 5196.97, 4.36, 36.42),
        ['ped'] = 'a_m_y_hippy_01',
        ['scenario'] = 'WORLD_HUMAN_AA_SMOKE',
        ['radius'] = 2.5,
        ['targetIcon'] = 'fas fa-leaf',
        ['targetLabel'] = 'Open Shop',
        ['products'] = Config.Products['fishshop'],
        ['showblip'] = true,
        ['blipsprite'] = 88,
        ['blipscale'] = 0.6,
        ['blipcolor'] = 3,
        ['delivery'] = vector4(-1593.88, 5196.97, 4.36, 36.42)
	},
}