local locales = {}

locales.en = {
    no_vehicles_nearby = "No vehicle nearby",
    empty_driverseat_required = "Vehicle must not have a driver",
    ev_requires_battery = "Electric vehicles must be charged with a booster battery",
    battery_on_petrol = "This can only be used on an electric vehicle",
    charge_on_petrol = "You can't charge a gasoline vehicle",
    invalid_mix = "You can't mix %s with %s",
    recharging = "Recharging",
    refueling = "Refueling",
    action_complete = "%s complete",
    battery_purchased = "You purchased a booster battery",
    jerrycan_purchased = "You purchased a jerry can",
    grab_fuel_lever = "~INPUT_PICKUP~ Grab Nozzle\n~INPUT_DETONATE~ Fuel Selection",
    attach_fuel_lever = "~INPUT_PICKUP~ Attach to Vehicle\n~INPUT_DETONATE~ Replace on Bowser",
    detach_fuel_lever = "~INPUT_DETONATE~ Remove from Vehicle",
    replace_fuel_lever = "~INPUT_DETONATE~ Replace on Bowser",
    leave_to_refill = "Leave the vehicle to refuel",
    ev_not_supported = "This station does not support electric vehicles",
    stock_depleted = "Stock depleted",
    no_pump_nearby = "No pump found",
    invalid_stock = "Not enough stock to facilitate this transaction",
    invalid_funds = "You don't have enough money to complete this transaction.",
    invalid_fuel = "Invalid fuel",
    vehicle_must_be_empty = "Vehicle must be empty to refuel.",
    no_valid_station_fuels = "This station has no valid fuels defined.",
    fuel_unit_long = "Litre",
    fuel_unit_short = "L",
    dollar_unit = "$",
    electric_unit_long = "Volts",
    electric_unit_short = "V",
    invalid_fuel_type = "This vehicle won't accept this fuel type.",
    fuel_type_not_supported = "This station doesn't distribute fuel acceptable for this vehicle.",
}

locales.es = {
    no_vehicles_nearby = "No hay vehiculos cerca",
    empty_driverseat_required = "No puede haber alguien conduciendo el vehiculo",
    ev_requires_battery = "Lo vehiculos electricos deben ser recargados con un cargador",
    battery_on_petrol = "Esto solo puede ser usado en un vehiculo electrico",
    charge_on_petrol = "No puedes cargar un vehiculo a combustion",
    invalid_mix = "No puedes mezclar %s con %s",
    recharging = "Recargando",
    refueling = "Llenando combustible",
    action_complete = "%s completado",
    battery_purchased = "Has comprado un cargador",
    jerrycan_purchased = "Has comprado un bidon de gasolina",
    grab_fuel_lever = "~INPUT_PICKUP~ Tomar la boquilla\n~INPUT_DETONATE~ Seleccionar combustible",
    attach_fuel_lever = "~INPUT_PICKUP~ Poner en vehiculo\n~INPUT_DETONATE~ Devolver al tanque",
    detach_fuel_lever = "~INPUT_DETONATE~ Quitar del vehiculo",
    replace_fuel_lever = "~INPUT_DETONATE~ Devolver al tanque",
    leave_to_refill = "Sal del vehiculo para llenar combustible",
    ev_not_supported = "Esta estación no tiene puestos de recarga para electricos",
    stock_depleted = "Sin existencias",
    no_pump_nearby = "No se encontró ninguna bomba",
    invalid_stock = "No hay suficiente stock para facilitar esta transacción",
    invalid_funds = "No tienes suficiente dinero para completar esta transacción.",
    invalid_fuel = "Combustible no válido",
    vehicle_must_be_empty = "El vehículo debe estar vacío para repostar.",   
    no_valid_station_fuels = "Esta estación no tiene tipos de gasolina validos.",     
    fuel_unit_long = "Litro(s)",
    fuel_unit_short = "L",
    dollar_unit = "$",
    electric_unit_long = "Voltios",
    electric_unit_short = "V",
}

locales.de = {
    no_vehicles_nearby = "Kein Fahrzeug in der Nähe",
    empty_driverseat_required = "Das Fahrzeug darf keinen Fahrer haben",
    ev_requires_battery = "Elektrofahrzeuge müssen mit einer Starterbatterie geladen werden",
    battery_on_petrol = "Dies kann nur in einem Elektrofahrzeug verwendet werden",
    charge_on_petrol = "Du kannst kein Benzinfahrzeug aufladen",
    invalid_mix = "Du kannst %s nicht mit %s mischen",
    recharging = "Aufladen",
    refueling = "Tanken",
    action_complete = "%s getankt",
    battery_purchased = "Du hast eine Zusatzbatterie gekauft",
    jerrycan_purchased = "Du hast einen Benzinkanister gekauft",
    grab_fuel_lever = "~INPUT_PICKUP~ Zapfhahn nehmen\n~INPUT_DETONATE~ Kraftstoff wählen",
    attach_fuel_lever = "~INPUT_PICKUP~ Zapfhahn ins Fahrzeug stecken\n~INPUT_DETONATE~ Zapfhahn wegstecken",
    detach_fuel_lever = "~INPUT_DETONATE~ Zapfhahn herausnehmen",
    replace_fuel_lever = "~INPUT_DETONATE~ Zapfhahn wegstecken",
    leave_to_refill = "Lasse das Fahrzeug zum Tanken stehen",
    ev_not_supported = "Diese Station unterstützt keine Elektrofahrzeuge",
    stock_depleted = "Lager erschöpft",
    no_pump_nearby = "Keine Pumpe gefunden",
    invalid_stock = "Nicht genügend Bestand, um diese Transaktion zu ermöglichen",
    invalid_funds = "Du hast nicht genug Geld, um diese Transaktion abzuschließen.",
    invalid_fuel = "Ungültiger Kraftstoff",
    vehicle_must_be_empty = "Das Fahrzeug muss zum Tanken leer sein.",
    no_valid_station_fuels = "Diese Tankstelle hat keine gängigen Kraftstoffe.",
    fuel_unit_long = "Liter",
    fuel_unit_short = "L",
    dollar_unit = "$",
    electric_unit_long = "Volt",
    electric_unit_short = "V",
}

locales.fr = {
    no_vehicles_nearby = "Pas de véhicule a proximité",
    empty_driverseat_required = "Le véhicule ne doit pas avoir de conducteur",
    ev_requires_battery = "Les véhicules électiques doivent être chargés via un booster",
    battery_on_petrol = "Le booster doit être utilisé sur un véhicule électrique",
    charge_on_petrol = "Tu ne peux pas recharger un véhicule thermique",
    invalid_mix = "Tu ne peux pas mélanger %s avec %s",
    recharging = "Rechargement",
    refueling = "Plein en cours",
    action_complete = "%s achevé",
    battery_purchased = "Tu as acheté un booster",
    jerrycan_purchased = "Tu as acheté un bidon d'essence",
    grab_fuel_lever = "~INPUT_PICKUP~ Prendre le pistolet\n~INPUT_DETONATE~ Selection de l'essence",
    attach_fuel_lever = "~INPUT_PICKUP~ Mettre le pistolet dans le réservoir\n~INPUT_DETONATE~ Remettre sur la pompe",
    detach_fuel_lever = "~INPUT_DETONATE~ Retirer le pistolet",
    replace_fuel_lever = "~INPUT_DETONATE~ Replacer sur la pompe",
    leave_to_refill = "Sors du véhicule pour faire le plein",
    ev_not_supported = "Cette station n'est pas adapté aux vehicules électriques",
    stock_depleted = "Stock faible",
    no_pump_nearby = "Pas de pompe à proximité",
    invalid_stock = "Pas assez d'essence en stock pour cette transaction",
    invalid_funds = "Tu n'as pas assez d'argent pour cette transaction.",
    invalid_fuel = "Essence invalide",
    vehicle_must_be_empty = "Le véhicule doit être vide afin de pouvoir faire le plein.",
    no_valid_station_fuels = "Cette station n'a pas d'essences définies.",
    fuel_unit_long = "Litres",
    fuel_unit_short = "L",
    dollar_unit = "$",
    electric_unit_long = "Volts",
    electric_unit_short = "V",
}

locales.dk = {
    no_vehicles_nearby = "Intet køretøj i nærheden",
    empty_driverseat_required = "Køretøjet må ikke have en chauffør",
    ev_requires_battery = "Elbiler skal oplades med et hjælpebatteri",
    battery_on_petrol = "Dette kan kun bruges på et elektrisk køretøj",
    charge_on_petrol = "Du kan ikke oplade en benzinbil",
    invalid_mix = "Du kan ikke blande %s med %s",
    genopladning = "Oplader",
    tankning = "tankning",
    action_complete = "%s fuldført",
    battery_purchased = "Du har købt et hjælpebatteri",
    jerrycan_purchased = "Du har købt en jerry can",
    grab_fuel_lever = "~INPUT_PICKUP~ Grib dysen ~INPUT_DETONATE~ Brændstofvalg",
    attach_fuel_lever = "~INPUT_PICKUP~ Fastgør til køretøj\n~INPUT_DETONATE~ Udskift på Bowser",
    detach_fuel_lever = "~INPUT_DETONATE~ Fjern fra køretøjet",
    replace_fuel_lever = "~INPUT_DETONATE~ Udskift på Bowser",
    leave_to_refill = "Forlad køretøjet for at tanke brændstof",
    ev_not_supported = "Denne station understøtter ikke elektriske køretøjer",
    stock_depleted = "Lagret opbrugt",
    no_pump_nearby = "Ingen pumpe fundet",
    invalid_stock = "Ikke nok lager til at lette denne transaktion",
    invalid_funds = "Du har ikke penge nok til at gennemføre denne transaktion.",
    invalid_fuel = "Ugyldigt brændstof",
    vehicle_must_be_empty = "Køretøjet skal være tomt for at kunne tanke brændstof.",
    no_valid_station_fuels = "Denne station har ingen gyldige brændstoffer defineret.",
    fuel_unit_long = "Liter",
    fuel_unit_short = "L",
    dollar_unit = "DKK",
    electric_unit_long = "Volt",
    electric_unit_short = "V",
}

--
-- Avoid editing below this line
--

ti.locales.set(locales)

labels = setmetatable({},{
    __index = function(t,k)
        return ti.locales.get(k)
    end
})