config = {
    -- shows the dimensions of nearby engines and the maximum engine dimensions for nearby vehicles.
    -- set to false if you don't want this command (why?).
    showDimsCommand = "showDims",
    showDimsExport = "showDims",
    showDimsHotkey = "H",

	allowNitrous = true,

	-- These jobs will have access to the showDims command
	showDimsJobs = {
		police = 1
	},

	-- These groups will have access to the showDims command
	showDimsGroups = {
		ballas = 2
	},

    -- Define custom engine sounds here.
    -- Must be string/non-hash.
    customSounds = {
        'npolchar',
    },

	-- Allow players to detach components and engines as inventory items
	detachAsItems = true,

	-- Auto generate machining recipes for each component type and each material in ti_vehicleTuning (see bottom of data\machiningrecipes.lua).
	autoGenerateRecipes = false,

	generatedDefaultTime = 2, 			-- how long should generated recipes take to perform?
	generatedDefaultMaterials = 10, 	-- how many materials should generated recipes require?
	prestigeMaterialMultiplier = 10, 	-- how how should the prestige value of a material be multiplied by before effecting the recipe material count?

	-- Define extra items for auto generated recipes per category.
	autoGeneratedRecipeItems = {
        block = { 		},
        intercooler = {},
        aspiration = {},
        nitrous = {},
        intake = {},
        fuel = {},
        heads = {},
        valves = {},
        crankshaft = {},
        conrods = {},
        pistons = {},
        headers = {},
        exhaust = {},
    },

	-- Maximum engine sizes given vehicle class.
    classRestrictions = {
    	[0] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[1] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[2] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[3] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[4] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[5] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[6] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[7] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[8] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[9] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[10] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[11] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[12] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[13] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[14] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[15] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[16] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[17] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[18] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[19] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[20] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    	[21] = {
    		w = 2.5,
    		d = 1.5,
    		h = 1.5
    	},
    }
}