QBShared = QBShared or {}
QBShared.Gangs = {
    none = { label = 'No Gang', grades = { ['0'] = { name = 'Unaffiliated' } } },
    level = {
        label = 'Level',
        grades = {
			['0'] = { name = '0' },
			['1'] = { name = '1' },
			['2'] = { name = '2' },
			['3'] = { name = '3' },
			['4'] = { name = '4' },
			['5'] = { name = '5' },
			['6'] = { name = '6' },
			['7'] = { name = '7' },
			['8'] = { name = '8' },
			['9'] = { name = '9' },
			['10'] = { name = '10' },
			['11'] = { name = '11' },
			['12'] = { name = '12' },
			['13'] = { name = '13' },
			['14'] = { name = '14' },
			['15'] = { name = '15' },
			['16'] = { name = '16' },
			['17'] = { name = '17' },
			['18'] = { name = '18' },
			['19'] = { name = '19' },
			['20'] = { name = '20' },
			['21'] = { name = '21' },
			['22'] = { name = '22' },
			['23'] = { name = '23' },
			['24'] = { name = '24' },
			['25'] = { name = '25' },
			['26'] = { name = '26' },
			['27'] = { name = '27' },
			['28'] = { name = '28' },
			['29'] = { name = '29' },
			['30'] = { name = '30' },
			['31'] = { name = '31' },
			['32'] = { name = '32' },
			['33'] = { name = '33' },
			['34'] = { name = '34' },
			['35'] = { name = '35' },
			['36'] = { name = '36' },
			['37'] = { name = '37' },
			['38'] = { name = '38' },
			['39'] = { name = '39' },
			['40'] = { name = '40' },
			['41'] = { name = '41' },
			['42'] = { name = '42' },
			['43'] = { name = '43' },
			['44'] = { name = '44' },
			['45'] = { name = '45' },
			['46'] = { name = '46' },
			['47'] = { name = '47' },
			['48'] = { name = '48' },
			['49'] = { name = '49' },
			['50'] = { name = '50' },
        },
    },
    lostmc = {
        label = 'The Lost MC',
        grades = {
            ['0'] = { name = 'Recruit' },
            ['1'] = { name = 'Enforcer' },
            ['2'] = { name = 'Shot Caller' },
            ['3'] = { name = 'Boss', isboss = true },
        },
    },
    ballas = {
        label = 'Ballas',
        grades = {
            ['0'] = { name = 'Recruit' },
            ['1'] = { name = 'Enforcer' },
            ['2'] = { name = 'Shot Caller' },
            ['3'] = { name = 'Boss', isboss = true },
        },
    },
    vagos = {
        label = 'Vagos',
        grades = {
            ['0'] = { name = 'Recruit' },
            ['1'] = { name = 'Enforcer' },
            ['2'] = { name = 'Shot Caller' },
            ['3'] = { name = 'Boss', isboss = true },
        },
    },
    cartel = {
        label = 'Cartel',
        grades = {
            ['0'] = { name = 'Recruit' },
            ['1'] = { name = 'Enforcer' },
            ['2'] = { name = 'Shot Caller' },
            ['3'] = { name = 'Boss', isboss = true },
        },
    },
    families = {
        label = 'Families',
        grades = {
            ['0'] = { name = 'Recruit' },
            ['1'] = { name = 'Enforcer' },
            ['2'] = { name = 'Shot Caller' },
            ['3'] = { name = 'Boss', isboss = true },
        },
    },
    triads = {
        label = 'Triads',
        grades = {
            ['0'] = { name = 'Recruit' },
            ['1'] = { name = 'Enforcer' },
            ['2'] = { name = 'Shot Caller' },
            ['3'] = { name = 'Boss', isboss = true },
        },
    }
}
